notifications:
  hipchat:
    rooms:
      secure: Pz5CQX/NtKLkk8c6kjhxipMS6kdQTj5jaeN9LC2k1IzERsqCYnx/nD2EV0cG4YJO0W3sMK3vaVgL5lLE3xHpe7wsLB/LWmxLY8QV0NJaSGOqqXAC4S5Yo7MRFd2S5fPWN7MC05SPpqiDveEle1fK6Gz7oHXSZxAFMyYnLRcaX3M=
language: php
php:
- '5.4'
- '5.5'
services:
- mysql
install:
- composer self-update
- composer install --no-interaction --no-scripts
before_script:
- "./bin/tests install"
script:
- "./bin/tests run --no-install"
deploy:
  provider: heroku
  api_key:
    secure: fkC2bEELMXojW0FFkWAlSayqR7GaB3bab/AwB+CW9vKyTd7qNs099mthWpV4iAaJXHQ64IYHvvfQ0IZ7VV/+JX3zsfzTKpcF70ArmQnERIW1cppV4ZtfxcRLHu70FP0Ab0Crenh/6wlj7NtmOfYVgi6L7lFQvNADqfPn2cYuXyk=
  app:
    master: ushahidi-platform-api-master
    release: ushahidi-platform-api-release
  on:
    repo: ushahidi/platform
    all_branches: true
