language: php
php:
  - "5.4"
services:
  - mysql
before_script:
  - composer install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive
  - mkdir application/cache application/logs
  - chmod 777 application/cache application/logs
  # db setup
  - mysql -e 'create database lamu_test;'
  - mv application/config/database.travis application/config/database.php
  - ./minion --task=migrations:run --up
  # 2.x db setup for import test
  - mysql -e 'create database zombie2x;'
  - curl https://72c9192a7b87de5fc63a-f9fe2e6be12470a7bff22b7693bc7329.ssl.cf1.rackcdn.com/lamu-ci-zombie2x.sql | mysql zombie2x
  # webserver setup
  - php -S localhost:8000 httpdocs/index.php &
  - sleep 3
script:
  - ./bin/behat --config application/tests/behat.yml
  - ./bin/phpunit -c application/tests/phpunit.xml
